### ISSUE TITLE
ViSPUnity.dll

### ISSUE THREAD

**Issue by Fardad77** [lagadic/visp_unity#27]
Hello folks,
I have followed Wiki instructions from https://github.com/lagadic/visp_unity/wiki/Generating-ViSP-wrapper-plugin to Generate the ViSP wrapper plugin.
But, after step "Build the wrapper linking to ViSP", I can not find the "**ViSPUnity.dll**" in: %VISP_WS%/visp_unity/vispWrapper-build-vc16/Release/
There are also some errors after the command "**cmake --build . --config Release**"
![image](https://user-images.githubusercontent.com/96995634/184858869-5165fd35-2ab2-4865-9cbc-c4cfacc1bfde.png)

Would you please advise me on how to fix it?

**Comment by fspindle** [comment]
I can't figure out why your error messages are relating to `mingw` while you are using `vc16`.
I suspect something wrong in your `Path` env variable.

Check first if ViSP is build and installed correctly:
- open a new `cmd` windows
- Run `C:\> dir %VISP_WS%\visp-build-vc16\install\x64\vc16\bin` should give the list of ViSP dll (`libvisp_core350.dll`...)
- Enter in the following folder `C:\> cd %VISP_WS\visp-build-vc16\tutorial\detection\tag\Release`
- Run `tutorial-apriltag-detector.exe`

If the binary is working, it means that ViSP is well installed. Otherwise, check if your `Path` env var contains `%VISP_WS%\visp-build-vc16\install\x64\vc16\bin`

Secondly concerning `vispWrapper`
- check your env var and remove everything related to `mingw` (maybe in your `Path` var)
- close all `cmd`windows
- remove `%VISP_WS%\visp_unity\vispWrapper-build-vc16` folder and try a new build from scratch

**Comment by fspindle** [comment]
Closed for now. Reopen if needed

**Comment by Fardad77** [comment]
Thank you Fabien @fspindle,
Yes, that is work as well!
